sudo: false
dist: trusty
language: python
python:
  - "3.9"

install:
  - pip install pipenv
  - pip install codecov
  - make install-dev

script:
  - make lint
  - make test

after_success:
  - codecov
