version: '3'

services:
  web:
    restart: always
    build: .
    env_file: .env
    command: flask run --host 0.0.0.0
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    links:
      - redis
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    sysctls:
      net.core.somaxconn: '65535'
