# fly.toml file generated for frosty-fog-6841 on 2023-07-11T12:34:23+01:00

app = "frosty-fog-6841"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
processes = []

[build]
  builder = "paketobuildpacks/builder:base"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
